// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3sLgO26FOK7mHy-JQpolQf6PUI001m_E',
    appId: '1:408124026921:web:96c43aca72420cace7ec38',
    messagingSenderId: '408124026921',
    projectId: 'smartbag-94038',
    authDomain: 'smartbag-94038.firebaseapp.com',
    databaseURL: 'https://smartbag-94038-default-rtdb.firebaseio.com',
    storageBucket: 'smartbag-94038.firebasestorage.app',
    measurementId: 'G-5LJLCCKFJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_8DXXFvr7_YYaZ1h2ABT5TCNNYMK64tY',
    appId: '1:408124026921:android:93b78966357ac188e7ec38',
    messagingSenderId: '408124026921',
    projectId: 'smartbag-94038',
    databaseURL: 'https://smartbag-94038-default-rtdb.firebaseio.com',
    storageBucket: 'smartbag-94038.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAejWZMqQO8vWd6qLvIisTUUd75fi-ULi0',
    appId: '1:408124026921:ios:0a241a2635586c2de7ec38',
    messagingSenderId: '408124026921',
    projectId: 'smartbag-94038',
    databaseURL: 'https://smartbag-94038-default-rtdb.firebaseio.com',
    storageBucket: 'smartbag-94038.firebasestorage.app',
    androidClientId: '408124026921-c2krpu7o1vac0abnb8pugcf9r6dt6e9i.apps.googleusercontent.com',
    iosClientId: '408124026921-7o0te23rnhfhof6ee4aie0ts16tkoodb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartbagx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAejWZMqQO8vWd6qLvIisTUUd75fi-ULi0',
    appId: '1:408124026921:ios:0a241a2635586c2de7ec38',
    messagingSenderId: '408124026921',
    projectId: 'smartbag-94038',
    databaseURL: 'https://smartbag-94038-default-rtdb.firebaseio.com',
    storageBucket: 'smartbag-94038.firebasestorage.app',
    androidClientId: '408124026921-c2krpu7o1vac0abnb8pugcf9r6dt6e9i.apps.googleusercontent.com',
    iosClientId: '408124026921-7o0te23rnhfhof6ee4aie0ts16tkoodb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartbagx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3sLgO26FOK7mHy-JQpolQf6PUI001m_E',
    appId: '1:408124026921:web:fc4c8757af852c62e7ec38',
    messagingSenderId: '408124026921',
    projectId: 'smartbag-94038',
    authDomain: 'smartbag-94038.firebaseapp.com',
    databaseURL: 'https://smartbag-94038-default-rtdb.firebaseio.com',
    storageBucket: 'smartbag-94038.firebasestorage.app',
    measurementId: 'G-SN71REFKP0',
  );
}
